<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to my wishlist</name>
   <tag></tag>
   <elementGuidId>42c034ea-d06c-4573-8fc0-8155ddecc283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/main/div[3]/div/div[6]/div/div[3]/div/div/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e1ca76ac-8203-49cb-a8ea-53aab788a1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>wishlist-button__add-to-wishlist</value>
      <webElementGuid>2d7a199d-c033-489d-ba06-d16a3355c883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wishlist-button button--block</value>
      <webElementGuid>2b426860-50f8-46a8-8a60-3f591449c779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to my wishlist     </value>
      <webElementGuid>c05fe80e-1df0-44a7-8cf8-e98fc127ddc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[1]/main[1]/div[@class=&quot;l-container u-margin-top--2 md:u-margin-top--4&quot;]/div[@class=&quot;l-grid&quot;]/div[@class=&quot;l-grid__cell l-grid__cell--9-col l-grid__cell--12-col-tablet l-grid__cell--12-col-phone&quot;]/div[@class=&quot;l-grid&quot;]/div[@class=&quot;l-grid__cell l-grid__cell--flex l-grid__cell--12-col l-grid__cell--6-col-desktop l-grid__cell--4-col-tablet&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card__section card__section--footer&quot;]/div[@class=&quot;u-text-align--right&quot;]/div[1]/button[@class=&quot;wishlist-button button--block&quot;]</value>
      <webElementGuid>89b759ce-736d-4be0-af58-357f4aeee98e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/main/div[3]/div/div[6]/div/div[3]/div/div/div/div/button</value>
      <webElementGuid>374f3faa-292e-4882-98c7-28e514f4a92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Lowest price on 11 Dec 2023)'])[1]/following::button[1]</value>
      <webElementGuid>7e1d94f2-a8d2-43f9-bc5f-7ed14d982bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,557'])[1]/following::button[1]</value>
      <webElementGuid>6f0c9263-f138-4243-b570-ac4a4324808f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='South Morocco Discovery'])[1]/preceding::button[1]</value>
      <webElementGuid>0c0d26c6-230a-4af0-8c60-cb3d55047f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/div/div/button</value>
      <webElementGuid>b0bdb638-e000-466c-8a3e-15c35a23d003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add to my wishlist     ' or . = 'Add to my wishlist     ')]</value>
      <webElementGuid>bbd84994-a75c-48d9-83aa-6c741d2b9b28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
