<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GMDDMapImage</name>
   <tag></tag>
   <elementGuidId>13f033bf-dc4e-4eff-9b7c-0c0d2562bf50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.imagery--cover-center.imagery.imagery--fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/main/div[3]/div/div[6]/div/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c4fc5307-652c-4ffd-abb9-c91db0289a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1100</value>
      <webElementGuid>0e82899a-edff-41d9-8385-b3d23eeb7f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>735</value>
      <webElementGuid>e2425b52-2367-4297-81aa-6b56c17efd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Map of Ultimate Galapagos: Central Islands (Grand Daphne) including Ecuador</value>
      <webElementGuid>9232d5bc-044f-432a-97c4-814cce4b4f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>985bd0c5-b11e-434f-9c8b-850e986afe31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imagery--cover-center imagery imagery--fluid</value>
      <webElementGuid>a9db0bf7-4955-4867-9b87-366409dac0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.contentstack.io/v3/assets/blt0de87ff52d9c34a8/bltd8816d61d8c0f4f6/654c1727a94c510407709280/GMDD_2024.gif</value>
      <webElementGuid>3912c731-63bd-491c-9ac8-d960244f9938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>343px</value>
      <webElementGuid>c3f81698-7136-4d35-a30a-088a68ed9ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[1]/main[1]/div[@class=&quot;l-container u-margin-top--2 md:u-margin-top--4&quot;]/div[@class=&quot;l-grid&quot;]/div[@class=&quot;l-grid__cell l-grid__cell--9-col l-grid__cell--12-col-tablet l-grid__cell--12-col-phone&quot;]/div[@class=&quot;l-grid&quot;]/div[@class=&quot;l-grid__cell l-grid__cell--flex l-grid__cell--12-col l-grid__cell--6-col-desktop l-grid__cell--4-col-tablet&quot;]/div[@class=&quot;card&quot;]/a[@class=&quot;card__content card__content--link&quot;]/div[@class=&quot;card__image&quot;]/img[@class=&quot;imagery--cover-center imagery imagery--fluid&quot;]</value>
      <webElementGuid>e04d713a-a33a-47a6-b6a6-c88d3aaa74dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/main/div[3]/div/div[6]/div/div/div/a/div/img</value>
      <webElementGuid>7c894447-d6ea-4356-ad56-807eb5962492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Map of Ultimate Galapagos: Central Islands (Grand Daphne) including Ecuador']</value>
      <webElementGuid>3a3d73b1-d33c-4bd5-aae1-bd7f92810f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>ab6da4a4-fb0f-451f-bc20-98b03a42236d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Map of Ultimate Galapagos: Central Islands (Grand Daphne) including Ecuador' and @src = 'https://images.contentstack.io/v3/assets/blt0de87ff52d9c34a8/bltd8816d61d8c0f4f6/654c1727a94c510407709280/GMDD_2024.gif']</value>
      <webElementGuid>385ac8b0-64bf-414b-a842-e3973724ca13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
