<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Discover your next adventure_autocomplete__input</name>
   <tag></tag>
   <elementGuidId>742a43f4-6428-4fab-89df-f2179b330e36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.autocomplete__input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/main/div[3]/div/div/form/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f95d47a-c23e-4837-ad32-33b45b44582e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Where do you want to go?</value>
      <webElementGuid>da269d53-1753-4fab-83af-fcf15948c8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search for a Destination, Trip name or Tour code</value>
      <webElementGuid>3d4da207-27fd-4613-9455-c73c2934f5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>autocomplete__input</value>
      <webElementGuid>b0874f1b-cdd4-4bfb-826f-ab141db221f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2a6be554-869b-46ab-b1b8-015a2e6f425d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3e2e1997-f438-4624-afdf-9451ef6eec70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete__input</value>
      <webElementGuid>fa97e1e5-daf9-4fbe-b504-9152f516b02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[1]/main[1]/div[@class=&quot;l-container u-margin-top--2 md:u-margin-top--4&quot;]/div[@class=&quot;l-grid&quot;]/div[@class=&quot;l-grid__cell l-grid__cell--12-col-desktop l-grid__cell--6-col-tablet l-grid__cell--4-col-phone&quot;]/form[1]/div[@class=&quot;search-autocomplete&quot;]/div[@class=&quot;autocomplete&quot;]/div[@class=&quot;autocomplete__input-wrapper&quot;]/input[@class=&quot;autocomplete__input&quot;]</value>
      <webElementGuid>594146a9-28ff-4e2f-b8ee-2eda1937dab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/main/div[3]/div/div/form/div/div/div/input</value>
      <webElementGuid>78dbfe32-c926-4a8a-af45-6d25429d7c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0cda21d1-5622-45f2-8497-c1e57ec2fc14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Where do you want to go?']</value>
      <webElementGuid>aab6cdc6-8be4-4b59-bded-cfae78bd04e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
