<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log in</name>
   <tag></tag>
   <elementGuidId>b51f6377-386f-4ad7-b0cb-5514baf8002b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/main/div[2]/div[2]/div[2]/div[2]/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>56992bd1-23b3-426e-b2ba-3c03267fb661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>27355cc2-baea-4a17-9dc6-5d6036b193e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>wishlist-page__login-link</value>
      <webElementGuid>aabca344-5623-414e-bc06-187a3588d321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-display--block md:u-display--inline</value>
      <webElementGuid>ee76cec8-1cbb-43be-b9f6-a78eb025ff11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>5c77fbd0-15b5-4429-8a2c-4a14ed0a7920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/main[1]/div[@class=&quot;u-margin-top--2&quot;]/div[@class=&quot;l-container&quot;]/div[@class=&quot;u-display--flex sm:u-flex-direction--row sm:u-justify-content--space-between u-padding-top--1-5 u-padding-bottom--1-5 sm:u-padding-bottom--2 u-flex-direction--column-reverse sm:u-flex-direction--row&quot;]/div[@class=&quot;u-display--block md:u-display--flex u-flex-direction--column u-justify-content--flex-end wishlist-page__create-my-account-button-container&quot;]/p[@class=&quot;u-margin-bottom--0 u-text-align--right&quot;]/a[@class=&quot;u-display--block md:u-display--inline&quot;]</value>
      <webElementGuid>23b36f24-6a9b-441b-bcb0-ce5685b93f19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/main/div[2]/div[2]/div[2]/div[2]/p/a</value>
      <webElementGuid>a8d30088-60ea-42c5-85e9-f52a8cf68c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log in')]</value>
      <webElementGuid>49a73273-0ac1-4d8a-ad46-8e9968c0a8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create my account'])[1]/following::a[1]</value>
      <webElementGuid>cb090777-4469-4741-8b2a-6b39a36a1204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove all trips'])[1]/following::a[1]</value>
      <webElementGuid>9ab614f3-8d41-48b6-9211-e00310f8bbb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vietnam Express Southbound'])[1]/preceding::a[1]</value>
      <webElementGuid>7cd3acbb-8489-4e32-a3f3-f23ad0201a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vietnam'])[3]/preceding::a[1]</value>
      <webElementGuid>8df2e6b7-70cc-4e9e-8e86-473578fc8254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log in']/parent::*</value>
      <webElementGuid>0a88641e-0993-4d66-8f7d-94c2316af9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>9e844578-e1e4-4315-b927-a0e96485d10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>b5d53ad5-fbf5-4414-9493-f93966b1c44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Log in' or . = 'Log in')]</value>
      <webElementGuid>3e4fdfbc-07df-49ac-8599-0e00ed067c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/main/div[2]/div[2]/div/div[2]/p/a</value>
      <webElementGuid>a918a07b-96c8-47c6-bfe6-a84f33d120c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore all trips'])[1]/following::a[1]</value>
      <webElementGuid>b6678c46-dac1-4d85-bdbd-540c7a169c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::a[1]</value>
      <webElementGuid>704277f5-b76a-4253-b44c-3f6af9dc08a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::a[1]</value>
      <webElementGuid>1daa4c69-e041-44ea-8805-854a725bb426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>d9a241a4-8f2d-4a21-ad3c-ec0b70b89364</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
