<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Africa</name>
   <tag></tag>
   <elementGuidId>d297e0bd-ad17-4616-b23d-6ff651ebabfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-bar']/div[2]/div/nav/div/nav/div/div/ul/li/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mega-menu__level-2-link.mega-menu__level-2-link--active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>91b6d6eb-e0e7-45fb-8c30-f5bbd095a780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>mega-menu__level-2-link</value>
      <webElementGuid>7a52db73-d96a-4f91-8f4d-05f56f1404b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mega-menu__level-2-link mega-menu__level-2-link--active</value>
      <webElementGuid>d766e880-2b92-42e4-b1fb-94a10e2b6468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Africa
                </value>
      <webElementGuid>5aaa0429-1a60-4b92-a596-2d03890cb27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-bar&quot;)/div[@class=&quot;header-bar__bottom u-display--none md:u-display--block&quot;]/div[@class=&quot;header-bar__container header-bar__container--flex&quot;]/nav[@class=&quot;header-bar__bottom-left&quot;]/div[1]/nav[@class=&quot;mega-menu&quot;]/div[@class=&quot;mega-menu__level-1 mega-menu__level-1--visible&quot;]/div[@class=&quot;mega-menu__level-2&quot;]/ul[@class=&quot;mega-menu__level-2-items&quot;]/li[@class=&quot;mega-menu__level-2-item&quot;]/button[@class=&quot;mega-menu__level-2-link mega-menu__level-2-link--active&quot;]</value>
      <webElementGuid>ac454cd4-2d25-4fb0-9839-86fc3a740f99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-bar']/div[2]/div/nav/div/nav/div/div/ul/li/button</value>
      <webElementGuid>9bb94334-a39f-4266-961f-b5c9d18d9721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purpose'])[1]/following::button[1]</value>
      <webElementGuid>2d6e4597-70c2-4050-b60d-670f2bc2f28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deals'])[1]/following::button[2]</value>
      <webElementGuid>47eecb09-d779-4aeb-a4ca-6118117efb3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Africa'])[2]/preceding::button[1]</value>
      <webElementGuid>46d27a3b-b8ff-4db8-bacb-6a2fcdaad7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Botswana'])[1]/preceding::button[1]</value>
      <webElementGuid>559ff179-4b26-4a66-aa37-8433bd820b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Africa']/parent::*</value>
      <webElementGuid>a32133eb-a19c-43af-a43a-2a3a0f66d648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/button</value>
      <webElementGuid>5bfa5149-e095-43c9-9cf7-9a0425ef79da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
            Africa
                ' or . = '
            Africa
                ')]</value>
      <webElementGuid>f0c6329f-d571-46b5-aa4f-23d06503168e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
