<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Destinations</name>
   <tag></tag>
   <elementGuidId>b718328f-760f-4dc5-95eb-91e4ded37c6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='header-bar__navigation-link-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header-bar__navigation-link-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9cf0aed4-d8c5-4b12-a275-8b1a3cd2f4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/top-destinations</value>
      <webElementGuid>4f95b0cb-e233-49cc-b523-bb6c4b4f08d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-bar__navigation-link-1</value>
      <webElementGuid>49915d0e-5f08-4f2f-8c2f-9a2944b3f699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>header-bar-menu-item</value>
      <webElementGuid>e908b3d1-8ae0-4595-a17a-b5414cba5634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-bar__navigation-link</value>
      <webElementGuid>2dac641b-99e2-4f15-98af-a029012a0dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Destinations
              </value>
      <webElementGuid>196cb2e1-145a-44a1-86a8-f5c49c2d15ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-bar__navigation-link-1&quot;)</value>
      <webElementGuid>53b82e1a-ed48-49ff-8389-beb680b4b729</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='header-bar__navigation-link-1']</value>
      <webElementGuid>37bf0927-fb1e-4396-a489-c25ca58e8205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-bar']/div[2]/div/nav/ul/li[2]/button</value>
      <webElementGuid>dc52c86a-124a-4ea7-9eca-f601da4ca0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Booking'])[1]/following::button[2]</value>
      <webElementGuid>9050a69c-6a93-45eb-8841-2184b1c61d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Wishlist'])[1]/following::button[2]</value>
      <webElementGuid>630c0438-045c-46a3-9617-2b453a3f102e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ways to travel'])[1]/preceding::button[1]</value>
      <webElementGuid>55e595a4-6048-4825-a80b-bab8c10dc575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deals'])[1]/preceding::button[2]</value>
      <webElementGuid>351b96f9-2a75-44e7-b992-8f627b720e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Destinations']/parent::*</value>
      <webElementGuid>bc06c5b3-986c-4432-9127-1e8897a0aada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button</value>
      <webElementGuid>a5563596-4d3b-4334-934c-c9cc4a04f9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@href = '/top-destinations' and @id = 'header-bar__navigation-link-1' and (text() = '
                Destinations
              ' or . = '
                Destinations
              ')]</value>
      <webElementGuid>fd8ebe52-b552-489b-87f6-7cfd9313c048</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
