<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Destinations</name>
   <tag></tag>
   <elementGuidId>b718328f-760f-4dc5-95eb-91e4ded37c6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header-bar__navigation-link-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='header-bar__navigation-link-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>36df18fc-e03e-4776-a671-eef8b27203ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/top-destinations</value>
      <webElementGuid>2bf59be8-d063-491b-831d-8a3c41b83a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-bar__navigation-link-1</value>
      <webElementGuid>146f5d9c-65e3-4ea8-b89d-eedc3b135729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>header-bar-menu-item</value>
      <webElementGuid>1ebe3f9e-8cca-404b-80ea-33d81f138e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-bar__navigation-link</value>
      <webElementGuid>8aafdba6-98a6-470b-bf74-29e48ee4f75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Destinations
              </value>
      <webElementGuid>4ea37d81-1ffb-4b03-96a3-1bfe83dcb58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-bar__navigation-link-1&quot;)</value>
      <webElementGuid>9390f67c-5766-45ec-a6cf-8e93d7370470</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='header-bar__navigation-link-1']</value>
      <webElementGuid>214049c1-1742-4871-8ca9-b0f1eab8f61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-bar']/div[2]/div/nav/ul/li[2]/button</value>
      <webElementGuid>d9ee15da-1999-4ae3-bf54-d8d48d84ea90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Booking'])[1]/following::button[2]</value>
      <webElementGuid>b32cd5b1-dcc5-4524-bdde-29639694c9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Wishlist'])[1]/following::button[2]</value>
      <webElementGuid>5c54d521-aae3-4376-b10c-0be7a5da0ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ways to travel'])[1]/preceding::button[1]</value>
      <webElementGuid>90c4b410-8ba8-4595-861f-55f486e60679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deals'])[1]/preceding::button[2]</value>
      <webElementGuid>22b30ce2-f10e-4e88-bd83-71ecc748c1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Destinations']/parent::*</value>
      <webElementGuid>c53a828e-9bc8-4197-843a-2be84192cafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button</value>
      <webElementGuid>9219b443-be4e-40e7-8d35-2fcf0b38b9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@href = '/top-destinations' and @id = 'header-bar__navigation-link-1' and (text() = '
                Destinations
              ' or . = '
                Destinations
              ')]</value>
      <webElementGuid>4da8972b-c1c0-4e7f-94a4-840c38612b30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
