<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(It, , s time for a new journey_e04c39</name>
   <tag></tag>
   <elementGuidId>5c9ac3cf-dfc8-4fa2-9b26-10b20d5b5e61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.autocomplete__input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/main/div/div/div[2]/div/div/div/div/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>530c61db-0309-444c-b14d-b4980110528b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Anywhere</value>
      <webElementGuid>16fff336-9c2b-4c8a-bec0-05d965573ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search for a Destination, Trip name or Tour code</value>
      <webElementGuid>5c854ee8-4507-4e13-be0c-0d4a361da642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>autocomplete__input</value>
      <webElementGuid>545bb33b-3fe6-43f8-b977-c3de4a797c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>910fd6f7-c0de-487a-8f50-ff6d8aa8df6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7ac8d9c2-7a4e-486e-8df4-5cd39b4d6444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete__input</value>
      <webElementGuid>7181fd26-d979-42bb-bcda-339a54c7b506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/main[1]/div[1]/div[@class=&quot;banner banner--xs-8-11 banner--sm-4-3 banner--md-7-3 banner--lg-7-3 banner--xl-7-3&quot;]/div[@class=&quot;banner__content&quot;]/div[@class=&quot;l-container u-height--full&quot;]/div[@class=&quot;home-banner&quot;]/div[@class=&quot;home-banner__content&quot;]/div[@class=&quot;find-trip&quot;]/div[@class=&quot;find-trip__autocomplete&quot;]/div[@class=&quot;autocomplete&quot;]/div[@class=&quot;autocomplete__input-wrapper&quot;]/input[@class=&quot;autocomplete__input&quot;]</value>
      <webElementGuid>f133ade7-54d0-4c62-b1be-250f93b88b06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/main/div/div/div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>dc8b62ae-c68d-49b8-91eb-ad3178e32da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7584173a-a809-4606-87eb-c37aaa8870c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Anywhere']</value>
      <webElementGuid>d04fc5b8-722a-45f9-9a58-60da5405b2b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
