<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search</name>
   <tag></tag>
   <elementGuidId>7062a932-4d9b-4b73-b8fd-baa572b4f22d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.find-trip__button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/main/div/div/div[2]/div/div/div/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d552bf3-d4ea-46a4-9ec9-c9fb46d91668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>find-trip__button-text</value>
      <webElementGuid>b54add06-4849-49f1-879a-d98c99a5c21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>db65de6e-1ac6-442b-a348-d5554d7f6763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/main[1]/div[1]/div[@class=&quot;banner banner--xs-8-11 banner--sm-4-3 banner--md-7-3 banner--lg-7-3 banner--xl-7-3&quot;]/div[@class=&quot;banner__content&quot;]/div[@class=&quot;l-container u-height--full&quot;]/div[@class=&quot;home-banner&quot;]/div[@class=&quot;home-banner__content&quot;]/div[@class=&quot;find-trip&quot;]/button[@class=&quot;button find-trip__button button--special&quot;]/span[@class=&quot;find-trip__button-text&quot;]</value>
      <webElementGuid>5262f02d-a656-428d-b95e-05c4333710dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/main/div/div/div[2]/div/div/div/div/button/span</value>
      <webElementGuid>0d11a6ca-a623-4e1f-82cf-e255acdaea76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear date'])[1]/following::span[1]</value>
      <webElementGuid>f4cc00d9-a66d-42c8-afcd-76ced1a3eff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dec'])[1]/following::span[12]</value>
      <webElementGuid>9f09af85-3277-4d0b-b45a-54639e468f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creating positive change through the joy of travel'])[1]/preceding::span[1]</value>
      <webElementGuid>62063776-2f32-4213-ab49-c594d60c4914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ways to travel'])[4]/preceding::span[1]</value>
      <webElementGuid>6129fcbe-529c-40db-a1d2-37707dd09c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>ccb44048-0cf3-4626-891a-69a407f20bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span</value>
      <webElementGuid>58ec0467-e12b-4ee4-85e0-4162f38a71d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>11294f16-8d45-4d67-b088-5ccd37e3989c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
