<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Booking number_bookingNumber</name>
   <tag></tag>
   <elementGuidId>183a676b-fa18-480d-9be9-4285d742adaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bookingNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bookingNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af150a2a-8cc1-4d7d-92fa-b89fc5703d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>647d7cce-2063-4092-9370-c4fa59a5bee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bookingNumber</value>
      <webElementGuid>99ec3319-b6ac-4b6f-9023-46b30a0b49cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>34784c3e-46b1-497c-a0c4-5ae66613a092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field field__input</value>
      <webElementGuid>3795d784-48f5-492a-9f2f-0876d9bf8733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bookingNumber&quot;)</value>
      <webElementGuid>49edabb3-f6d2-4782-b228-32af991beb45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bookingNumber']</value>
      <webElementGuid>8c2de49c-b74a-49b3-834d-1eefba3d66b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>97c73263-453e-4cb6-85dd-0152863a3752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ce7eea49-84e8-465d-bb0f-68002fb17675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bookingNumber']</value>
      <webElementGuid>3fa5205a-87c6-426a-9083-e064ad187ada</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
