<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ruchira Weerakkody</name>
   <tag></tag>
   <elementGuidId>4958567b-3241-41b4-a75d-10bfe49f0268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[2]/div/div/div/div[3]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div/div/table/tbody/tr[3]/th/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>20eeb401-4b01-4bee-b56e-d7d35e293ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refid</name>
      <type>Main</type>
      <value>recordId</value>
      <webElementGuid>c71b2799-1f38-4793-a076-e0b53069a235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-special-link</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c056e53-5c84-4fdb-962a-c730b49c1915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ruchira Weerakkody</value>
      <webElementGuid>ffcf2844-82aa-450f-9cbf-efe782853d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navigable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b30402d9-f4cd-4fd0-aaf4-fc5f6247dda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>20cbf807-ab3b-4b81-9608-860741281f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ownerid</name>
      <type>Main</type>
      <value>3157:0</value>
      <webElementGuid>962cef48-09de-4782-b897-0119c6d19c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordid</name>
      <type>Main</type>
      <value>0036D00000mE9oxQAC</value>
      <webElementGuid>ca0747a4-0e26-4dcf-af65-82353881b9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>134d70ed-1e73-4362-ade9-e66c7fa66bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lightning/r/0036D00000mE9oxQAC/view</value>
      <webElementGuid>0f462b32-dc3f-435d-b93e-6cea21f9790a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-truncate outputLookupLink slds-truncate outputLookupLink-0036D00000mE9oxQAC-3157:0 forceOutputLookup</value>
      <webElementGuid>ea5bca4d-ec59-4beb-b012-28d9a10889ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>3168:0</value>
      <webElementGuid>8545c05a-6e0d-40a3-a328-242458ebd4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-class</name>
      <type>Main</type>
      <value>forceOutputLookup</value>
      <webElementGuid>57477c22-a3af-4eab-98fe-0ea214dc8cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ruchira Weerakkody</value>
      <webElementGuid>9f2b4885-2367-481c-9eea-d8bc432e2f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;slds-grid forceSearchBaseSearchPage forceSearchSearchPageDesktop&quot;]/div[@class=&quot;searchScrollerWrapper&quot;]/div[@class=&quot;resultsWrapper slds-template__content slds-scrollable--y&quot;]/div[@class=&quot;forceSearchResultsRegion slds-grid slds-grid--vertical&quot;]/div[@class=&quot;predictedResultsOuterWrapper slds-grid slds-grid_vertical slds-col slds-is-relative forceSearchPredictedResults&quot;]/div[@class=&quot;predictedResultsWrapper slds-grid slds-grid_vertical slds-col slds-is-relative slds-m-bottom_medium&quot;]/div[@class=&quot;enabled uiScroller forceSearchResultsMultiScope scroller-wrapper scroll-vertical native&quot;]/div[@class=&quot;scroller&quot;]/div[@class=&quot;resultsMultiWrapper&quot;]/div[@class=&quot;slds-grid slds-grid_vertical&quot;]/div[@class=&quot;resultsItem slds-col slds-no-flex slds-m-bottom_small&quot;]/div[@class=&quot;forcesearch-results-grid-lvm-desktop slds-table_joined  test-listViewManager slds-card slds-card_boundary slds-grid slds-grid--vertical forceListViewManager forceSearchResultsGridLVM&quot;]/div[@class=&quot;slds-grid listDisplays safari-workaround-anchor&quot;]/div[@class=&quot;listViewContainer safari-workaround&quot;]/div[@class=&quot;slds-col slds-no-space forceListViewManagerPrimaryDisplayManager&quot;]/div[@class=&quot;autoHeight col-0-wrap col-1-wrap col-2-wrap col-3-wrap col-4-wrap col-5-wrap col-6-wrap col-7-wrap col-8-wrap col-9-wrap hideRowNumberColumn hideSelection forceListViewManagerGrid&quot;]/div[@class=&quot;listViewContent slds-table--header-fixed_container&quot;]/div[@class=&quot;uiScroller scroller-wrapper scroll-bidirectional native&quot;]/div[@class=&quot;scroller actionBarPlugin&quot;]/div[@class=&quot;slds-table--edit_container slds-is-relative  inlineEdit--disabled keyboardMode--active inlineEditGrid forceInlineEditGrid&quot;]/table[@class=&quot;slds-table forceRecordLayout slds-table--header-fixed slds-table--edit slds-table--bordered resizable-cols slds-table--resizable-cols uiVirtualDataTable&quot;]/tbody[1]/tr[3]/th[@class=&quot;slds-cell-edit cellContainer&quot;]/span[@class=&quot;slds-grid slds-grid--align-spread&quot;]/a[@class=&quot;slds-truncate outputLookupLink slds-truncate outputLookupLink-0036D00000mE9oxQAC-3157:0 forceOutputLookup&quot;]</value>
      <webElementGuid>1fcc2284-d983-486e-b6a6-79336639bdac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/div/div/div/div[3]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div/div/table/tbody/tr[3]/th/span/a</value>
      <webElementGuid>30399588-f34b-4372-9f7e-981904bc2e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ruchira Weerakkody')])[3]</value>
      <webElementGuid>de09f0d2-bcd3-4202-bd7f-42ee148ff6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Actions'])[2]/following::a[1]</value>
      <webElementGuid>e70f62f7-6014-42c7-8707-cb68d62a6557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ruchira007@gmail.com'])[4]/following::a[2]</value>
      <webElementGuid>23c2409f-44ae-45b4-b9d8-70dc6a33ddb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ruchira Weerakkody'])[5]/preceding::a[1]</value>
      <webElementGuid>f17da082-0ee7-466e-925d-be96880c0a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ruchira007@gmail.com'])[5]/preceding::a[2]</value>
      <webElementGuid>3d17e529-5cab-45ea-b316-b5924de1c056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lightning/r/0036D00000mE9oxQAC/view')]</value>
      <webElementGuid>0698c0dc-65dc-48eb-94ac-d456e314f789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/th/span/a</value>
      <webElementGuid>57763ed3-e501-480f-94a9-4a3c6466320c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Ruchira Weerakkody' and @href = '/lightning/r/0036D00000mE9oxQAC/view' and (text() = 'Ruchira Weerakkody' or . = 'Ruchira Weerakkody')]</value>
      <webElementGuid>15891090-1321-436c-9536-6bdb9d2ffd36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_4']/div/div/div[2]/div/div/div/div[3]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div/div/table/tbody/tr/th/span/a</value>
      <webElementGuid>ebecfd5e-67db-4fce-88ab-b951a6fe0a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ruchira Weerakkody')]</value>
      <webElementGuid>cd4c7bb5-9b13-45e2-bd32-48b09244d628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[2]/following::a[1]</value>
      <webElementGuid>46c78909-9921-49de-8e8c-b62dbbb2f23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Column Actions'])[17]/following::a[1]</value>
      <webElementGuid>0a9c02ea-f5da-402b-a4e5-bf84c3d0d3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ruchira Weerakkody'])[3]/preceding::a[1]</value>
      <webElementGuid>e79e4919-995b-40e1-8b59-821dbf59eeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ruchira007@gmail.com'])[3]/preceding::a[2]</value>
      <webElementGuid>1f1858df-f2d3-4d1e-b02b-5660d6f730ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lightning/r/0036D00000kXNKKQA4/view')]</value>
      <webElementGuid>e7f98a1c-89c1-4a06-a205-edd302371526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/span/a</value>
      <webElementGuid>53780960-1421-4194-8526-988045258fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Ruchira Weerakkody' and @href = '/lightning/r/0036D00000kXNKKQA4/view' and (text() = 'Ruchira Weerakkody' or . = 'Ruchira Weerakkody')]</value>
      <webElementGuid>b4b99c39-e435-4979-ae0a-e17420d77ceb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
