<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ruchira Weerakkody_1</name>
   <tag></tag>
   <elementGuidId>84f67c44-5b27-4a24-b82d-5c56fcea601c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[2]/div/div/div/div[3]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div/div/table/tbody/tr[4]/th/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7830087b-b870-4c14-9e1c-1a9b73d4061d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refid</name>
      <type>Main</type>
      <value>recordId</value>
      <webElementGuid>e3ee6fc8-30a2-41b3-b41a-185d378feb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-special-link</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>850c4929-f872-4be6-a406-dd3f61173628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ruchira Weerakkody</value>
      <webElementGuid>cd613ef3-fa52-4e73-8dc7-62d88cadf92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navigable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>43abf0a7-4cd2-4790-9c93-f41394df20dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>69dbe90c-37b3-45ec-8566-6025e2757493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ownerid</name>
      <type>Main</type>
      <value>3210:0</value>
      <webElementGuid>315803dd-d25a-46fc-881c-e0cc1bd2c9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordid</name>
      <type>Main</type>
      <value>0036D00000mE9oxQAC</value>
      <webElementGuid>686cb5d5-a911-4fd5-b787-3bfa11c1c447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>3773f35d-4cc5-43ac-ac0d-599b93867728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lightning/r/0036D00000mE9oxQAC/view</value>
      <webElementGuid>fbd9e82b-4d82-471d-b3a4-cf4479228e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-truncate outputLookupLink slds-truncate outputLookupLink-0036D00000mE9oxQAC-3210:0 forceOutputLookup</value>
      <webElementGuid>95c46886-6b8e-4f09-83d1-05b6f2e2f553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>3221:0</value>
      <webElementGuid>216583e8-d86b-4b07-81fe-8db4b06637d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-class</name>
      <type>Main</type>
      <value>forceOutputLookup</value>
      <webElementGuid>2b964911-fe45-4dd8-aac4-7da252becf70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ruchira Weerakkody</value>
      <webElementGuid>acb2e949-ea44-404f-a49f-9c7626c72a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;slds-grid forceSearchBaseSearchPage forceSearchSearchPageDesktop&quot;]/div[@class=&quot;searchScrollerWrapper&quot;]/div[@class=&quot;resultsWrapper slds-template__content slds-scrollable--y&quot;]/div[@class=&quot;forceSearchResultsRegion slds-grid slds-grid--vertical&quot;]/div[@class=&quot;predictedResultsOuterWrapper slds-grid slds-grid_vertical slds-col slds-is-relative forceSearchPredictedResults&quot;]/div[@class=&quot;predictedResultsWrapper slds-grid slds-grid_vertical slds-col slds-is-relative slds-m-bottom_medium&quot;]/div[@class=&quot;enabled uiScroller forceSearchResultsMultiScope scroller-wrapper scroll-vertical native&quot;]/div[@class=&quot;scroller&quot;]/div[@class=&quot;resultsMultiWrapper&quot;]/div[@class=&quot;slds-grid slds-grid_vertical&quot;]/div[@class=&quot;resultsItem slds-col slds-no-flex slds-m-bottom_small&quot;]/div[@class=&quot;forcesearch-results-grid-lvm-desktop slds-table_joined  test-listViewManager slds-card slds-card_boundary slds-grid slds-grid--vertical forceListViewManager forceSearchResultsGridLVM&quot;]/div[@class=&quot;slds-grid listDisplays safari-workaround-anchor&quot;]/div[@class=&quot;listViewContainer safari-workaround&quot;]/div[@class=&quot;slds-col slds-no-space forceListViewManagerPrimaryDisplayManager&quot;]/div[@class=&quot;autoHeight col-0-wrap col-1-wrap col-2-wrap col-3-wrap col-4-wrap col-5-wrap col-6-wrap col-7-wrap col-8-wrap col-9-wrap hideRowNumberColumn hideSelection forceListViewManagerGrid&quot;]/div[@class=&quot;listViewContent slds-table--header-fixed_container&quot;]/div[@class=&quot;uiScroller scroller-wrapper scroll-bidirectional native&quot;]/div[@class=&quot;scroller actionBarPlugin&quot;]/div[@class=&quot;slds-table--edit_container slds-is-relative  inlineEdit--disabled keyboardMode--active inlineEditGrid forceInlineEditGrid&quot;]/table[@class=&quot;slds-table forceRecordLayout slds-table--header-fixed slds-table--edit slds-table--bordered resizable-cols slds-table--resizable-cols uiVirtualDataTable&quot;]/tbody[1]/tr[4]/th[@class=&quot;slds-cell-edit cellContainer&quot;]/span[@class=&quot;slds-grid slds-grid--align-spread&quot;]/a[@class=&quot;slds-truncate outputLookupLink slds-truncate outputLookupLink-0036D00000mE9oxQAC-3210:0 forceOutputLookup&quot;]</value>
      <webElementGuid>f55d708c-6fcc-45e9-8073-7781344b5580</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/div/div/div/div[3]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div/div/table/tbody/tr[4]/th/span/a</value>
      <webElementGuid>77d2b0a6-f056-4765-9fbe-6961db88ecdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ruchira Weerakkody')])[3]</value>
      <webElementGuid>082fb736-14ec-4e86-a56c-ddf5b487220e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Actions'])[3]/following::a[1]</value>
      <webElementGuid>765ac8de-0939-4209-8d4d-77eef9526b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ruchira007@gmail.com'])[5]/following::a[2]</value>
      <webElementGuid>a4d80d7e-8058-4faf-bf04-0de8d92c4d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ruchira Weerakkody'])[5]/preceding::a[1]</value>
      <webElementGuid>709d2d05-43e8-44a2-bfa3-eade2ccfbe8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ruchira007@gmail.com'])[6]/preceding::a[2]</value>
      <webElementGuid>3a98bc83-dc16-4901-9569-8f769a3c0108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lightning/r/0036D00000mE9oxQAC/view')]</value>
      <webElementGuid>6f717e01-3a58-45d7-aece-7359375dd31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/th/span/a</value>
      <webElementGuid>6cefcbe4-bdec-43e0-912d-b766cf6021ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Ruchira Weerakkody' and @href = '/lightning/r/0036D00000mE9oxQAC/view' and (text() = 'Ruchira Weerakkody' or . = 'Ruchira Weerakkody')]</value>
      <webElementGuid>94c8f852-4f04-4565-8f67-926776286b18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
