<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>4206d251-662e-4096-a47a-0cc54f604554</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.slds-button.slds-button_neutral.search-button.slds-truncate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de743007-ed53-4d80-abbf-0eb6e33a5881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d460b83b-0c0e-45d5-8f93-c118dc010a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_neutral search-button slds-truncate</value>
      <webElementGuid>bc7b7787-52bc-4d9e-8bf2-e6c604b75e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>06c71b2f-04de-4b85-a5dd-bceb0f2946f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>113:0;p</value>
      <webElementGuid>100aea09-dc7a-403c-99c9-e574e45ccee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>1394d580-2e1e-4e89-a730-41bddec31bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oneHeader&quot;)/div[@class=&quot;slds-global-header slds-grid slds-grid--align-spread&quot;]/div[@class=&quot;slds-global-header__item slds-global-header__item--search&quot;]/div[@class=&quot;slds-grid slds-size_1-of-1 slds-grid--align-center forceSearchAssistant&quot;]/button[@class=&quot;slds-button slds-button_neutral search-button slds-truncate&quot;]</value>
      <webElementGuid>3d8cdc02-9156-43d7-86e8-f3d7687938cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>a424d9c1-0efb-437e-9248-f309a3664b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='oneHeader']/div[2]/div[2]/div/button</value>
      <webElementGuid>2532749d-247a-4b34-8e19-e6a7786df799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intrepid Service'])[1]/following::button[1]</value>
      <webElementGuid>29a30ee0-c9a8-4257-802e-56a2e52c7681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Main Content'])[1]/following::button[1]</value>
      <webElementGuid>1c455696-eb7d-477d-a435-15dbcd45f4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intrepid Service'])[2]/preceding::button[1]</value>
      <webElementGuid>5f6931c0-94a1-4687-8732-dc901f1511d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add favorite'])[1]/preceding::button[1]</value>
      <webElementGuid>36d1c229-0e04-440f-bbc8-bdcd83307f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search...']/parent::*</value>
      <webElementGuid>db541cb1-8f40-4b22-9a19-bcc8515a87b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2a5d3882-57b8-4708-b501-3c21312dae8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Search...' or . = 'Search...')]</value>
      <webElementGuid>bde5a72f-8abe-4332-ae31-3feeff25d4ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
