<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Travel deals</name>
   <tag></tag>
   <elementGuidId>ec413928-d031-465f-95c6-852c5cfb6d7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='anchor-navigation__navigation-link-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#anchor-navigation__navigation-link-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>438e728d-e2e8-475b-94d6-e0265f24190d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anchor-navigation__navigation-link-1</value>
      <webElementGuid>fe66dfb0-522d-4f5a-87e9-d446048213a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>anchor-navigation-menu-item</value>
      <webElementGuid>3d1ed222-e30d-410d-a3b9-40840b0fe36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>anchor-navigation__navigation-link</value>
      <webElementGuid>6309e91d-7e3f-4507-84fc-8ceab4cf7b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Travel deals
                </value>
      <webElementGuid>5c546df4-f755-4282-b354-645ba67ad5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anchor-navigation__navigation-link-1&quot;)</value>
      <webElementGuid>5b2b1c3a-8f0b-425f-a476-dc0a45b20020</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='anchor-navigation__navigation-link-1']</value>
      <webElementGuid>11650440-39f6-4c6f-ae9c-3d1cfdc8bb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/main/div[3]/div/div/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>235af1ef-bcac-483c-9e9c-5694929d4c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/following::button[1]</value>
      <webElementGuid>7374b00b-700d-4f1e-af74-367f63273463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Botswana'])[4]/following::button[2]</value>
      <webElementGuid>8387b56d-ca44-4a22-9ea7-7b831faf48e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our trips'])[1]/preceding::button[1]</value>
      <webElementGuid>88bdb557-edab-4ac3-912d-4f9c71d796ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trip reviews'])[1]/preceding::button[2]</value>
      <webElementGuid>61416611-bfe3-46a3-afb9-b9cb7691c749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Travel deals']/parent::*</value>
      <webElementGuid>91753393-fd13-42c9-9d16-63327e372520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>76e86c4f-8dfd-465a-8f30-ad87cb6181ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'anchor-navigation__navigation-link-1' and (text() = '
                  Travel deals
                ' or . = '
                  Travel deals
                ')]</value>
      <webElementGuid>ccf272ea-f98a-4c79-b066-01dab070edfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
