<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Articles</name>
   <tag></tag>
   <elementGuidId>69283a23-4cfa-45d8-9282-6f447a640c5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='anchor-navigation__navigation-link-4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#anchor-navigation__navigation-link-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5002f868-38af-49ce-a9a5-ce1fc45126e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anchor-navigation__navigation-link-4</value>
      <webElementGuid>46e15fe6-ed80-45d5-bdfc-46b140934bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>anchor-navigation-menu-item</value>
      <webElementGuid>5afc8203-54b2-4e6d-8c6a-f4836593181c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>anchor-navigation__navigation-link</value>
      <webElementGuid>95f745a3-729e-449b-a4b4-99976ede8088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Articles
                </value>
      <webElementGuid>8b24d780-c185-4c9d-9e54-15b74e657a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anchor-navigation__navigation-link-4&quot;)</value>
      <webElementGuid>db3c9530-c801-4463-8e2b-75392b9e28d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='anchor-navigation__navigation-link-4']</value>
      <webElementGuid>6ff752e9-959b-4a37-a4ef-eb035613a418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/main/div[3]/div/div/div/div/div/div/div[5]/div/button</value>
      <webElementGuid>c7172e88-36fa-4567-a5ef-20c05916feca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trip reviews'])[1]/following::button[1]</value>
      <webElementGuid>95b3c7f9-c4dc-4884-a82d-aae4950fb765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our trips'])[1]/following::button[2]</value>
      <webElementGuid>a8520a65-9c7f-472e-b95b-250f3e890864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQs'])[1]/preceding::button[1]</value>
      <webElementGuid>a4bc6513-3b3b-457e-85da-f6bdd2987bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Botswana travel deals'])[1]/preceding::button[2]</value>
      <webElementGuid>52ed57b2-2dd4-4311-a35d-e296f0191c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Articles']/parent::*</value>
      <webElementGuid>a4641314-91c1-479d-8ee3-8f097865ebc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>c0848c07-a065-42d4-8dde-e33d4d8511c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'anchor-navigation__navigation-link-4' and (text() = '
                  Articles
                ' or . = '
                  Articles
                ')]</value>
      <webElementGuid>71cc0bd5-6781-4b6a-b33f-87c4bbb6455b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
