<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Trip reviews</name>
   <tag></tag>
   <elementGuidId>8e89a1e2-00d8-48f5-8de2-bcf19510c853</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='anchor-navigation__navigation-link-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#anchor-navigation__navigation-link-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f05a382c-5c43-4011-98e3-0aa062b700c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anchor-navigation__navigation-link-3</value>
      <webElementGuid>3498d516-807d-4400-a03f-0e7033e368a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>anchor-navigation-menu-item</value>
      <webElementGuid>1599cedc-520a-4152-a2a5-0ec503935cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>anchor-navigation__navigation-link</value>
      <webElementGuid>19af4a41-bc87-44be-81e5-d3df1587e5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Trip reviews
                </value>
      <webElementGuid>aab85181-fc3c-438e-b321-c80a66fb9294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anchor-navigation__navigation-link-3&quot;)</value>
      <webElementGuid>70e8bdc1-f500-4fdc-8080-07975b942397</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='anchor-navigation__navigation-link-3']</value>
      <webElementGuid>88b2b72c-d2a0-4ec1-b162-5bcc374347e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/main/div[3]/div/div/div/div/div/div/div[4]/div/button</value>
      <webElementGuid>9c1115a3-6afd-4429-90d8-2394da34f529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our trips'])[1]/following::button[1]</value>
      <webElementGuid>6ac0a555-6d31-4417-b9aa-49643da972ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travel deals'])[1]/following::button[2]</value>
      <webElementGuid>79294657-b172-47b4-bde4-3e98562c2664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Articles'])[1]/preceding::button[1]</value>
      <webElementGuid>d62b8c70-b0a2-47ac-b924-e1fe0c40f33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQs'])[1]/preceding::button[2]</value>
      <webElementGuid>02fe42c2-7595-4e8c-b88b-51e906a21e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Trip reviews']/parent::*</value>
      <webElementGuid>86da5447-6825-4e7f-b1cf-f4ccc5bff846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>2fcc3014-f45e-414f-aa75-1f2fa911895e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'anchor-navigation__navigation-link-3' and (text() = '
                  Trip reviews
                ' or . = '
                  Trip reviews
                ')]</value>
      <webElementGuid>06deb267-91d3-4362-b904-3b773df6fd7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
