<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Overview</name>
   <tag></tag>
   <elementGuidId>95c7385e-bd5e-4c2c-8096-614258b47117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='anchor-navigation__navigation-link-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#anchor-navigation__navigation-link-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14d350b9-a7ad-42b5-8f65-76507ea6dcf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anchor-navigation__navigation-link-0</value>
      <webElementGuid>e30c51b7-5628-4473-b65b-47ff2f22825d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>anchor-navigation-menu-item</value>
      <webElementGuid>140efaac-d51c-47fc-952e-e8682e548054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>anchor-navigation__navigation-link</value>
      <webElementGuid>b1903bc9-f584-46f2-baa1-97785a995444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Overview
                </value>
      <webElementGuid>1f6d6616-a144-43b6-93db-d56ca499822b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anchor-navigation__navigation-link-0&quot;)</value>
      <webElementGuid>e89ca1cf-89dd-44f3-9ea2-90ffcb1802f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='anchor-navigation__navigation-link-0']</value>
      <webElementGuid>4f5515dc-500d-4420-bad0-fd864315845b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/main/div[3]/div/div/div/div/div/div/div/div/button</value>
      <webElementGuid>83fe5327-abb8-49ca-9cd9-5aaeaafcd71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Botswana'])[4]/following::button[1]</value>
      <webElementGuid>3e50b903-2c0a-4cc0-bf1e-59dcd730d933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Botswana'])[3]/following::button[1]</value>
      <webElementGuid>c0dc69b5-30b2-48c0-b68a-2c1932646318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travel deals'])[1]/preceding::button[1]</value>
      <webElementGuid>eaa20f60-a1a5-4693-a70e-769d1ecdc010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our trips'])[1]/preceding::button[2]</value>
      <webElementGuid>2b952c76-507b-4817-8fbd-e3478dadef6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Overview']/parent::*</value>
      <webElementGuid>6a2be382-6067-4b05-a0d0-70277c806a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/button</value>
      <webElementGuid>20e20e24-0949-41c9-8f7e-63b3eb3d17f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'anchor-navigation__navigation-link-0' and (text() = '
                  Overview
                ' or . = '
                  Overview
                ')]</value>
      <webElementGuid>c1463b1f-812c-4215-80e4-cd7755a9cec4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
