<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_2024</name>
   <tag></tag>
   <elementGuidId>e7a367a0-1155-480e-a5b9-51b8c41b888a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.date-button-select__button.button--secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='2024']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4caa7ddb-af5e-4a70-bfb4-59ffa43a813d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button date-button-select__button button--secondary</value>
      <webElementGuid>4ea03a77-bac3-4eb1-91f5-532b2867e75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>614b504d-08eb-4039-abe9-6de427cbc868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>cb5910be-aab2-4193-97b2-945f69df8f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dates-&amp;-availabilities&quot;)/div[1]/div[@class=&quot;u-margin-bottom--2 xs:u-padding-left--1 xs:u-padding-right--1 sm:u-padding-left--0 sm:u-padding-right--0&quot;]/div[@class=&quot;date-button-select&quot;]/div[@class=&quot;date-button-select__years&quot;]/button[@class=&quot;button date-button-select__button button--secondary&quot;]</value>
      <webElementGuid>d404861d-edc4-43a7-b72f-5a958c59293e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='2024']</value>
      <webElementGuid>d770ad8c-9337-44e0-8a0b-3cce994944e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dates-&amp;-availabilities']/div/div/div[2]/div/button[2]</value>
      <webElementGuid>27822d58-16a3-4a17-a92e-abd2df00a97f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prices may go up, so secure your trip today'])[1]/following::button[2]</value>
      <webElementGuid>a001a8a7-25e1-4786-8aa6-c474618d30b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dates and availability'])[2]/following::button[2]</value>
      <webElementGuid>23976e1a-d527-4595-ae4f-10dbbd20e822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan'])[1]/preceding::button[1]</value>
      <webElementGuid>ebd6cbc7-b18f-4567-be8e-26d276a97e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feb'])[1]/preceding::button[2]</value>
      <webElementGuid>b4a3c7f0-e9f8-4c57-85fc-12a9e4ebd7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2024']/parent::*</value>
      <webElementGuid>dba64c25-94eb-4c76-9a99-1432b2510f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button[2]</value>
      <webElementGuid>ffb7cbe9-d4d7-4bbd-bdcf-8469f7b0818a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '2024' or . = '2024')]</value>
      <webElementGuid>17957258-51f9-4e2d-b12a-c79c4341d263</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
