<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_2024</name>
   <tag></tag>
   <elementGuidId>68c30b42-0236-42a2-bd89-b6efeb01fc70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.date-button-select__button.button--secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='2024']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fda7a29e-c864-432a-8c9c-896f1a639add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button date-button-select__button button--secondary</value>
      <webElementGuid>e7a46ec8-1645-4ba0-9ce8-a063f078efd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>5dec509c-ebdc-458f-ac9a-22079be260bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>78378b6e-89ed-401d-9080-9635e65a69b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dates-&amp;-availabilities&quot;)/div[1]/div[@class=&quot;u-margin-bottom--2 xs:u-padding-left--1 xs:u-padding-right--1 sm:u-padding-left--0 sm:u-padding-right--0&quot;]/div[@class=&quot;date-button-select&quot;]/div[@class=&quot;date-button-select__years&quot;]/button[@class=&quot;button date-button-select__button button--secondary&quot;]</value>
      <webElementGuid>9241e7aa-4b9d-4a66-91ac-dc0509bd5822</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='2024']</value>
      <webElementGuid>e41d0b97-3ff4-43c8-99c1-4a69ce7b345c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dates-&amp;-availabilities']/div/div/div[2]/div/button[2]</value>
      <webElementGuid>e7628203-9f50-4ce4-8409-dc26bf6edda8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prices may go up, so secure your trip today'])[1]/following::button[2]</value>
      <webElementGuid>66151f7f-6f6d-4747-97f7-4bab46550864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dates and availability'])[2]/following::button[2]</value>
      <webElementGuid>5a17b9ea-294a-4927-a5d0-009a1863a071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan'])[1]/preceding::button[1]</value>
      <webElementGuid>c474bc91-e8c0-4f03-97d4-6f72b4d5ce5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feb'])[1]/preceding::button[2]</value>
      <webElementGuid>167b9cad-c641-46dd-a001-f76d851fd54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2024']/parent::*</value>
      <webElementGuid>37a5929f-909b-4827-bcef-64213ca324b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button[2]</value>
      <webElementGuid>0517bdaf-918a-4e47-a427-ac8b03767882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '2024' or . = '2024')]</value>
      <webElementGuid>77289a0c-a104-4c08-b9b2-70c24869968d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
