<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Available</name>
   <tag></tag>
   <elementGuidId>de6007dd-d081-48a0-af30-55c6d0826416</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Dates-&amp;-availabilities']/div/div[2]/div[5]/button/div/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10a86673-b341-4cfe-b8f7-4e9ebe3b88b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>departures-day-header__options</value>
      <webElementGuid>18b77983-5b51-4446-9323-8d1f91fbc752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
        Available
      </value>
      <webElementGuid>f863f8e8-76aa-4fe1-95ca-aa4761b2ffcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dates-&amp;-availabilities&quot;)/div[1]/div[@class=&quot;accordion&quot;]/div[@class=&quot;accordion__item&quot;]/button[@class=&quot;accordion__item-header&quot;]/div[@class=&quot;accordion__item-header-title&quot;]/div[@class=&quot;departures-day-header&quot;]/div[@class=&quot;departures-day-header__options&quot;]</value>
      <webElementGuid>2dfb9ea6-6d33-4495-951e-460c20ad4cb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dates-&amp;-availabilities']/div/div[2]/div[5]/button/div/div/div[4]</value>
      <webElementGuid>9253c21d-eeb3-447f-a0b5-dc8f411c691a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jul 2024'])[5]/following::div[2]</value>
      <webElementGuid>3b551b07-8feb-4a74-a7be-4d45095d0b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tuesday 23'])[1]/following::div[2]</value>
      <webElementGuid>88ea762e-6c3a-4aba-ba7c-2beef4c1f4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[8]/preceding::div[3]</value>
      <webElementGuid>ca7235b5-cb0f-4a63-a9cb-2b36a1c4829b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button/div/div/div[4]</value>
      <webElementGuid>a1e6be7d-81f5-47b8-ae24-7e97e1b6ebab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 
        Available
      ' or . = ' 
        Available
      ')]</value>
      <webElementGuid>41f43a52-598a-42d4-b5e8-9c51238285fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
