<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pay Now</name>
   <tag></tag>
   <elementGuidId>bbb2f9a3-9f56-49c9-9ac6-3ae92b39c04a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='enabledSubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#enabledSubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>06f2ae9b-6f5f-4547-ae42-56b49b1af538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f3b7ad50-bc68-4e6f-ae2b-9cc449332343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>enabledSubmit</value>
      <webElementGuid>e3b960d1-364a-4f99-b7f7-f2c28a704231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>continue-button</value>
      <webElementGuid>b3ae29b5-6e8e-4071-a635-e5598df1c8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--primary</value>
      <webElementGuid>2d0ae673-d339-4787-be0c-b6b8037252d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Pay Now
                            </value>
      <webElementGuid>412334ca-ff66-4108-bd3e-e9c7bfca3c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enabledSubmit&quot;)</value>
      <webElementGuid>b7a925c2-f12b-4710-b696-009fa932a090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='enabledSubmit']</value>
      <webElementGuid>e8a7cabc-c47a-4d53-9446-b978841af36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='transaction_form']/div/div/div[2]/div[3]/button</value>
      <webElementGuid>2c916fc1-2451-48a5-88d1-bd7f0fe3637a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[1]</value>
      <webElementGuid>36663ff8-2003-4328-9933-a0a289a1b170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Booking conditions'])[1]/following::button[1]</value>
      <webElementGuid>a07bc92c-f179-466c-b99c-51422810be8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Booking summary'])[1]/preceding::button[1]</value>
      <webElementGuid>28495026-c6b9-4e2a-af4d-0c51eb4c5613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trips'])[1]/preceding::button[2]</value>
      <webElementGuid>59f20c7a-9199-427d-9430-d0e8825992fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pay Now']/parent::*</value>
      <webElementGuid>3692f7eb-3ee2-4763-a39b-33b982ab3367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>f0050f80-a9f8-46a0-a91b-4262fd90d395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'enabledSubmit' and (text() = '
                                Pay Now
                            ' or . = '
                                Pay Now
                            ')]</value>
      <webElementGuid>a9755f9c-10dd-48c9-bc08-897b8d709bcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
