<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Would you like to support the communitie_9ddc31</name>
   <tag></tag>
   <elementGuidId>84585a2b-55ae-42cd-80a6-485e21557c01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='services_form']/div/div[2]/div/div[4]/div/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>6d560b43-f62b-47bb-85de-50bc7e3ad5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>would-you-like-to-donate</value>
      <webElementGuid>e25cdd0f-e3c7-4f81-ba6e-8a26532078f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-margin-top--0</value>
      <webElementGuid>341018d6-d984-4965-9dc8-660a7487dcc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Would you like to support the communities we visit?</value>
      <webElementGuid>d76ad644-130e-4014-8254-2fd4719ac265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;services_form&quot;)/div[@class=&quot;l-container&quot;]/div[@class=&quot;l-grid&quot;]/div[@class=&quot;l-grid__cell l-grid__cell--8-col l-grid__cell--8-col-tablet&quot;]/div[@class=&quot;card card--large&quot;]/div[@class=&quot;card__content&quot;]/div[@class=&quot;card__text&quot;]/div[@class=&quot;card__section card__section--content&quot;]/h4[@class=&quot;u-margin-top--0&quot;]</value>
      <webElementGuid>0c86d83e-8c53-4497-8560-f630303c40f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='services_form']/div/div[2]/div/div[4]/div/div/div/h4</value>
      <webElementGuid>8d745d06-7fe4-40b8-b9be-4ce1d50b1830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Would you like help with extras?'])[1]/following::h4[1]</value>
      <webElementGuid>2bcf3f93-6633-427b-b70a-0504e1c504fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add transfers'])[1]/following::h4[2]</value>
      <webElementGuid>b979d3fd-9bd7-4af6-9420-2886f2d1b964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[2]/preceding::h4[1]</value>
      <webElementGuid>c37f8084-6e37-47dd-8865-3e933f4b8902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Would you like to support the communities we visit?']/parent::*</value>
      <webElementGuid>25535e0c-7cb6-4ef0-b616-2c4f92062595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/h4</value>
      <webElementGuid>f01646fb-426b-425b-afe7-2cd31fc6234b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Would you like to support the communities we visit?' or . = 'Would you like to support the communities we visit?')]</value>
      <webElementGuid>33bdb766-cf8f-4b39-a47e-3175e9e0c0b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
