<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_pYour browser does not support iframes.p_1</name>
   <tag></tag>
   <elementGuidId>0765a034-9fa3-411e-a858-b6eb1411a7cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.l-grid__cell.l-grid__cell--5-col.l-grid__cell--4-col-tablet.l-grid__cell--2-col-phone > span.card-payment__field > iframe.js-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='prebooking-payment']/div[4]/div/span/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d021a06d-0e3e-49b8-846b-b00375fb0d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkoutshopper-test.adyen.com/checkoutshopper/securedfields/pub.v2.8015795649981265.aHR0cHM6Ly9ib29raW5ncy5pbnRyZXBpZHRyYXZlbC5jb20udWF0LmludGVybmFs.ZXcGa92vLjRGmdQU83MgafUfVp-ype2LoTClniYKN5A/4.5.1/securedFields.html?type=card&amp;d=aHR0cHM6Ly9ib29raW5ncy5pbnRyZXBpZHRyYXZlbC5jb20udWF0LmludGVybmFs</value>
      <webElementGuid>bc7f324a-0d81-4bff-9a7a-f5c26eb99d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-iframe</value>
      <webElementGuid>15123c56-bb23-47ff-94a7-70782a880110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Iframe for expiry date</value>
      <webElementGuid>67951555-fc32-471a-8942-aebb428965e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>84a67dc8-6f88-4a62-ab0e-06bfb6426dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>48ba1cc8-02b1-4d5c-b0ff-d20d129953be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;p>Your browser does not support iframes.&lt;/p></value>
      <webElementGuid>3c28c875-790e-4d93-8dec-0e5e58eb9d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prebooking-payment&quot;)/div[@class=&quot;l-grid&quot;]/div[@class=&quot;l-grid__cell l-grid__cell--5-col l-grid__cell--4-col-tablet l-grid__cell--2-col-phone&quot;]/span[@class=&quot;card-payment__field&quot;]/iframe[@class=&quot;js-iframe&quot;]</value>
      <webElementGuid>2800ce54-d6e6-4331-a2ea-2d71e68d89f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prebooking-payment']/div[4]/div/span/iframe</value>
      <webElementGuid>3dda248d-42e9-4d1b-9191-8f4aea6f5aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card number'])[1]/following::iframe[1]</value>
      <webElementGuid>bfaf5765-7c3f-45c3-b311-7429259ae6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cardholder name'])[2]/following::iframe[2]</value>
      <webElementGuid>cec824b3-22a9-42c6-ae28-121489391d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiry date'])[1]/preceding::iframe[1]</value>
      <webElementGuid>7c0ff63c-5760-4004-a990-45ae9db2c889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CVV/CVC'])[1]/preceding::iframe[2]</value>
      <webElementGuid>6b1bc05e-d7d9-4586-9064-f930b81ad41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/iframe</value>
      <webElementGuid>3b3006a2-1d29-4734-90b4-f1340ce3c719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://checkoutshopper-test.adyen.com/checkoutshopper/securedfields/pub.v2.8015795649981265.aHR0cHM6Ly9ib29raW5ncy5pbnRyZXBpZHRyYXZlbC5jb20udWF0LmludGVybmFs.ZXcGa92vLjRGmdQU83MgafUfVp-ype2LoTClniYKN5A/4.5.1/securedFields.html?type=card&amp;d=aHR0cHM6Ly9ib29raW5ncy5pbnRyZXBpZHRyYXZlbC5jb20udWF0LmludGVybmFs' and @title = 'Iframe for expiry date' and (text() = '&lt;p>Your browser does not support iframes.&lt;/p>' or . = '&lt;p>Your browser does not support iframes.&lt;/p>')]</value>
      <webElementGuid>58b21f3b-2584-44d1-b4a8-808ac13d4ab1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
