<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cardholder name_transactionFormcardHo_ecd32b</name>
   <tag></tag>
   <elementGuidId>f47c5cfa-9588-460c-a486-777c115e6423</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transactionForm[cardHolderName]-id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71294c85-f3dc-4a87-812a-6d5031adfa90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c824e58b-96f3-4f2b-b7e0-47278c50b75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transactionForm[cardHolderName]-id</value>
      <webElementGuid>84dce3c5-a6da-4c6b-8765-5e2473873bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transactionForm[cardHolderName]</value>
      <webElementGuid>67a01a5b-06bc-45d0-97e4-d27ad05d831d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>387b3b10-3cb0-4d83-acc6-fc9c6e8d8945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field field__input</value>
      <webElementGuid>b1aedc98-b77a-43cd-accf-824970e4ced7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transactionForm[cardHolderName]-id&quot;)</value>
      <webElementGuid>a109bc23-4c45-4766-8efe-34a54e159644</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transactionForm[cardHolderName]-id']</value>
      <webElementGuid>acab77d0-d961-4a34-a8af-abb8606f9f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prebooking-payment']/div[2]/div/div/div/input</value>
      <webElementGuid>0634d3bf-a6c2-4e14-8d89-c58fe529afb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/input</value>
      <webElementGuid>de2b089b-54f4-450b-aa80-fde7a9e7ac4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'transactionForm[cardHolderName]-id' and @name = 'transactionForm[cardHolderName]']</value>
      <webElementGuid>1144d677-e9fd-47b9-9e8a-834cf8e58115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
