<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_bookingFormpassengers0emailAddress</name>
   <tag></tag>
   <elementGuidId>8e9b0f1f-71d1-4e2c-b49d-52443c475f1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bookingForm_passengers_0_emailAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bookingForm_passengers_0_emailAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0cd4509-5e88-4924-95ab-56c4176ecbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6e839c3-f09f-4fb1-9c35-db13a4c6f4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bookingForm_passengers_0_emailAddress</value>
      <webElementGuid>1ebbc51d-5f1b-4d67-989b-f6ec9a20a6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bookingForm[passengers][0][emailAddress]</value>
      <webElementGuid>3f5f9c79-dfc4-4642-9c44-3d3bbe5db0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>c36b1ace-5417-49f5-9c41-4a36157e4e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field field__input</value>
      <webElementGuid>20f1b118-371d-4118-95a0-376b5a37437c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bookingForm_passengers_0_emailAddress&quot;)</value>
      <webElementGuid>c009bc3b-ee2a-469c-b9d8-5575090cd7d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bookingForm_passengers_0_emailAddress']</value>
      <webElementGuid>b09de98b-bf0e-4a09-b82a-e56e61f1e388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/form/div/div/div[2]/div/div/div/div/div/div/div/div[6]/div/div/input</value>
      <webElementGuid>ded11c33-e589-453e-9037-8f5d3bee03c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>5188eba0-d089-4195-8192-96d05c83ff90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bookingForm_passengers_0_emailAddress' and @name = 'bookingForm[passengers][0][emailAddress]']</value>
      <webElementGuid>188231bd-9cf7-4326-b840-239617038a5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
