<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , encryptedSecurityCode, , ))_encryptedSecurityCode</name>
   <tag></tag>
   <elementGuidId>b636f69b-12a7-400b-8612-9a16e2e0808b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#encryptedSecurityCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='encryptedSecurityCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>641395d5-08a4-4f39-a7c8-c0eee7bd084b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>encryptedSecurityCode</value>
      <webElementGuid>085e26e1-b22b-498c-8938-b7db73f004fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fieldtype</name>
      <type>Main</type>
      <value>encryptedSecurityCode</value>
      <webElementGuid>c958345b-17c6-40f2-b6f6-d44fd7fce5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70010090-1dd8-4b02-a6dc-39527824ee1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>857db212-98e1-4172-b155-a6727abee025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>6b86cc14-5d42-4128-bae5-98e4f9213842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-csc</value>
      <webElementGuid>394d656a-d54e-449f-ab15-5986d4f7a728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>3 digits</value>
      <webElementGuid>4b5b731a-64df-49d4-96e2-5ecd5a26112f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Security code</value>
      <webElementGuid>55da74e5-a2cf-4b28-8395-b8b5de5e4f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>90c8698d-96d5-47a5-af17-2b5a87ab7404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f23d1ef5-aa63-4145-be06-00cfafe47f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>encryptedSecurityCode-ariaError</value>
      <webElementGuid>a871fa94-e59c-45e6-a8b0-b1ef6a5aee2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-iframe-input input-field</value>
      <webElementGuid>056b12c7-03b5-4cde-a212-57995654024c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>gsf</value>
      <webElementGuid>e721e063-e964-4154-9e41-88c11638a889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;encryptedSecurityCode&quot;)</value>
      <webElementGuid>d7ce6872-d2a6-47b7-bf99-bdc7f7bcddaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Intrepid Travel Booking Engine/iframe_pYour browser does not support iframes.p_1_2</value>
      <webElementGuid>12bdcfbe-acee-49bf-b20e-5a22823045ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='encryptedSecurityCode']</value>
      <webElementGuid>b243edae-e0a7-4fd5-92e4-635f35fdfcd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>b28ce68e-7db8-4b01-8542-6da8bb3428dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'encryptedSecurityCode' and @type = 'text' and @placeholder = '3 digits']</value>
      <webElementGuid>b0583b25-9976-438a-b0cf-9e78bb241307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
