<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_State  Province_bookingFormpassengers0county</name>
   <tag></tag>
   <elementGuidId>cb1ac332-801c-4340-9b17-19658692f47b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bookingForm_passengers_0_county</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bookingForm_passengers_0_county']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f599b3b0-5b58-4b9d-b27e-eac3268cbc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>753768e3-ff15-424e-a584-26c96c92ca2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bookingForm_passengers_0_county</value>
      <webElementGuid>52f3c898-ef00-499e-9709-299c4161e195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bookingForm[passengers][0][county]</value>
      <webElementGuid>b40ba9ce-7939-460c-be4a-cf6c728560dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>510e6dee-ab17-41e0-8d5a-2020f45d9ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field field__input</value>
      <webElementGuid>b92dde91-77c8-4731-8a9d-46f2a02b0b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bookingForm_passengers_0_county&quot;)</value>
      <webElementGuid>35844427-793b-4c6f-a41e-16952de0e428</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bookingForm_passengers_0_county']</value>
      <webElementGuid>bf7354db-2c01-4825-96c6-95bb523ea4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/form/div/div/div[2]/div/div/div/div/div/div/div/div[11]/div/div/input</value>
      <webElementGuid>1be92ff6-9664-471e-9c5a-592554404459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/input</value>
      <webElementGuid>cbf5414a-d703-4f90-b4a3-7fa4343c5741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bookingForm_passengers_0_county' and @name = 'bookingForm[passengers][0][county]']</value>
      <webElementGuid>0e5deac5-dee5-4c05-b384-7e8158eb1191</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
