<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name (as per passport)_bookingFo_24ba78</name>
   <tag></tag>
   <elementGuidId>5af7f0c0-b238-4c61-9295-03b59e5f5812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bookingForm_passengers_0_lastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bookingForm_passengers_0_lastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7bfbe693-227f-49d3-9048-6d8792a6e53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ec4d474-a97b-4523-b30d-09e4bdf704bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bookingForm_passengers_0_lastName</value>
      <webElementGuid>33a486f6-7089-4cb8-8f20-b8791828a0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bookingForm[passengers][0][lastName]</value>
      <webElementGuid>7fc1710f-3088-4a82-a1a2-7bf145200719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>4b6cf683-860a-43ff-9f11-46e61f6deab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-field field__input</value>
      <webElementGuid>e55b94ff-43fe-46ce-9e14-9b8c6fcfdeb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bookingForm_passengers_0_lastName&quot;)</value>
      <webElementGuid>14664ae3-8c7b-40e7-af85-6a26c291ee2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bookingForm_passengers_0_lastName']</value>
      <webElementGuid>cc8886cd-d40c-4ac9-b9c5-a395c41dad37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/form/div/div/div[2]/div/div/div/div/div/div/div/div[4]/div[3]/div/input</value>
      <webElementGuid>4201ddfa-13e4-4797-bb5d-10599d5d9ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>e5de96bf-8bcc-438b-a5b4-91b696c7cd47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bookingForm_passengers_0_lastName' and @name = 'bookingForm[passengers][0][lastName]']</value>
      <webElementGuid>3a6f8665-d214-42b1-8eef-0438feb325ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
