<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , encryptedExpiryDate, , ))_encryptedExpiryDate</name>
   <tag></tag>
   <elementGuidId>11fc8d89-68f4-4fe7-ac7d-691d479e364c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#encryptedExpiryDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='encryptedExpiryDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b33d9837-db98-4d05-a69c-88c10a585f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>encryptedExpiryDate</value>
      <webElementGuid>c6faa001-a231-493b-b71c-e449eaa2916b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fieldtype</name>
      <type>Main</type>
      <value>encryptedExpiryDate</value>
      <webElementGuid>b5b6da21-3a67-4513-9f5d-cc9f38a01591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02dd48c9-8983-4e4f-9458-9f7ec21c8815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>bf625bab-85ed-4df6-9e40-a91941daf59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5429022c-c4ed-4b78-b35e-e2cdbb4ce339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-exp</value>
      <webElementGuid>4ff20ddb-12b1-467e-91bc-5b80d6fa7828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/YY</value>
      <webElementGuid>ba9675e4-9bc5-4df6-925a-d5bf732b09e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Expiry date</value>
      <webElementGuid>e9e36175-26be-4de4-83f8-61781f7e7508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ae7bb0d1-cb19-4215-a812-89c71a7dbafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2891ece2-7f7b-4c68-82a3-7faea8c931db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>encryptedExpiryDate-ariaError</value>
      <webElementGuid>541e74a1-a3bf-40b0-8fb6-7cf23e09b3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-iframe-input input-field</value>
      <webElementGuid>a812cdb8-e89e-4e13-b986-a102cc31f983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>gsf</value>
      <webElementGuid>54f74c86-798a-4b26-8d5e-abd7462b7baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;encryptedExpiryDate&quot;)</value>
      <webElementGuid>fc482ef3-d2ee-44c0-bc0f-ce7db47ad2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Intrepid Travel Booking Engine/iframe_pYour browser does not support iframes.p_1</value>
      <webElementGuid>10fe2103-0a2a-4870-8d93-c53dda0287ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='encryptedExpiryDate']</value>
      <webElementGuid>2f5247bb-1458-4a8b-b92e-b53f23b5e41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ba2817fc-1254-4fd3-a8ea-c0463bf2627c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'encryptedExpiryDate' and @type = 'text' and @placeholder = 'MM/YY']</value>
      <webElementGuid>6d8b9ce3-37c6-4245-b858-2f0c0fff5ad9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
