<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , encryptedCardNumber, , ))_encryptedCardNumber</name>
   <tag></tag>
   <elementGuidId>cafb9fe2-5c03-470d-94ed-11f444244499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#encryptedCardNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='encryptedCardNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83e55f83-71d7-43b4-bd81-74a29ad6a421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>encryptedCardNumber</value>
      <webElementGuid>8cd38f24-9e2f-4e58-b3a4-c24ca713f97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fieldtype</name>
      <type>Main</type>
      <value>encryptedCardNumber</value>
      <webElementGuid>d6b56979-cfdc-489c-8705-e676b3d73041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8800598c-836f-4ec4-9c87-2622819b5e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>2b9bccad-2b9e-42b7-b539-f7ac6343df92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>d916115d-4cb0-41b0-8f25-191bd10e0169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-number</value>
      <webElementGuid>9ad60f3f-8103-4f33-93e8-3f17e6fba15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1234 5678 9012 3456</value>
      <webElementGuid>d20a3cd7-471b-4e8c-9cda-7b6a22d53543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Card number</value>
      <webElementGuid>6de37e50-db2e-4535-9c31-ecf7ce72414e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b8f2f582-2cb1-43cb-9a83-46716b4937fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4fd9b471-2139-4e14-93ae-b15b19ac1412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>encryptedCardNumber-ariaError</value>
      <webElementGuid>88c7e832-6a87-4505-8ad7-26b47cd8a14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-iframe-input input-field</value>
      <webElementGuid>d14c8d94-867d-4dfb-adb8-0b936875ebb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>gsf</value>
      <webElementGuid>fd883b27-1d9c-4ac4-84af-837a40e5185c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;encryptedCardNumber&quot;)</value>
      <webElementGuid>74b63c05-bdb1-4ba0-8e2b-3d2ccc422c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Intrepid Travel Booking Engine/iframe_pYour browser does not support iframes.p</value>
      <webElementGuid>fb3e61d8-c91a-4b4d-99bf-c1981b6f1704</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='encryptedCardNumber']</value>
      <webElementGuid>087c850a-b331-43a2-b7d8-e359bdaee313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>fed96300-ceb1-4595-9725-bb8d5a217259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'encryptedCardNumber' and @type = 'text' and @placeholder = '1234 5678 9012 3456']</value>
      <webElementGuid>1ff4a0cc-7058-4929-ba37-5d6f94a29aa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
