<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MrMrsMsMiss</name>
   <tag></tag>
   <elementGuidId>fa7cd392-61d1-432b-8032-5e724e5d45af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bookingForm_passengers_0_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='bookingForm_passengers_0_title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9d7e1cd3-f6dc-4910-95cd-2bef6871580c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4047bee2-7950-4566-836d-8ee80b9c88a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bookingForm_passengers_0_title</value>
      <webElementGuid>2b8b972d-9b83-416e-8e3b-25fb1b1bd6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bookingForm[passengers][0][title]</value>
      <webElementGuid>a666ee5a-770a-444b-a5fc-a448d98b848f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>select-field</value>
      <webElementGuid>64aef666-e967-4e0b-a1bc-e89e19e6bd94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-field__input field__input</value>
      <webElementGuid>f1b977b8-8d40-43c2-b606-53748c54e01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MrMrsMsMiss</value>
      <webElementGuid>5cd80714-6280-4501-98d2-a3ea1ce6e5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bookingForm_passengers_0_title&quot;)</value>
      <webElementGuid>9d6dbb03-52c4-4f17-88cd-3991c1d82b64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='bookingForm_passengers_0_title']</value>
      <webElementGuid>3a3e44f3-d31f-4925-a9d7-b760e4a67059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/form/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>bf34fb5e-3678-4c27-b863-a868c14fd2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title *'])[1]/following::select[1]</value>
      <webElementGuid>4a0b4e05-ae85-4f36-b1ed-e63d4fb49441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal details'])[1]/following::select[1]</value>
      <webElementGuid>ff7d3c0d-514a-4f0a-b1ee-01460c9bab7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why do we need this?'])[1]/preceding::select[1]</value>
      <webElementGuid>c08e18b1-aea0-4b9d-9b94-d3c6537a24ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name (as per passport)*'])[1]/preceding::select[1]</value>
      <webElementGuid>c0f8233f-ae33-4cca-b2c1-f7787f4f8575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>64d978d3-f8e3-4aab-84e8-93a39806dec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@type = 'text' and @id = 'bookingForm_passengers_0_title' and @name = 'bookingForm[passengers][0][title]' and (text() = 'MrMrsMsMiss' or . = 'MrMrsMsMiss')]</value>
      <webElementGuid>9aab9402-37b5-430c-829b-ac2180c30a14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
