<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_January February March April May Jun_0a059c</name>
   <tag></tag>
   <elementGuidId>612041a6-383d-4c35-a114-ff9c47649057</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='month-bookingForm[passengers][0][dateOfBirth][month]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>052b7cb6-fc4c-4dff-8d4e-ecfbb1d20b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bookingForm[passengers][0][dateOfBirth][month]</value>
      <webElementGuid>57548a05-ff9c-45d2-a224-0223d07103a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>month-bookingForm[passengers][0][dateOfBirth][month]</value>
      <webElementGuid>de0a4250-8a9a-4919-985a-1c1930f581f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>select-month</value>
      <webElementGuid>bd776ca6-dbc4-437c-b89f-a204c87b5026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>date-select-field__input field__input</value>
      <webElementGuid>7e724d05-3524-4d86-9b7f-9fb9155bc76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> January February March April May June July August September October November December</value>
      <webElementGuid>3e0cb02e-1b64-474b-a9e5-161edf5b0bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;month-bookingForm[passengers][0][dateOfBirth][month]&quot;)</value>
      <webElementGuid>c9f4501a-3c5c-4b0d-8c0a-db7e469f8862</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='month-bookingForm[passengers][0][dateOfBirth][month]']</value>
      <webElementGuid>42be42ae-5470-4d64-9f25-b90058e35826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/form/div/div/div[2]/div/div/div/div/div/div/div/div[5]/div/div[2]/div[2]/div/select</value>
      <webElementGuid>8eb9e27a-d1b5-4a9a-93bb-3c4c072ab90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day'])[1]/following::select[1]</value>
      <webElementGuid>e55ab081-e6e8-4c50-a82b-48471ed84a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of birth *'])[1]/following::select[2]</value>
      <webElementGuid>9fd1ac26-bd11-4b6e-a619-4314b92da709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Month'])[1]/preceding::select[1]</value>
      <webElementGuid>f9a82f45-4600-419e-9df7-abbba1aea689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/preceding::select[2]</value>
      <webElementGuid>c4f72c92-9120-4ea3-82cf-a6466ecd6eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>aa553e71-b15e-4467-8e1d-cbd6463fbe8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'bookingForm[passengers][0][dateOfBirth][month]' and @id = 'month-bookingForm[passengers][0][dateOfBirth][month]' and (text() = ' January February March April May June July August September October November December' or . = ' January February March April May June July August September October November December')]</value>
      <webElementGuid>588c48c2-37be-4c01-a7cf-8823d7aec5c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
