<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_3,353.00</name>
   <tag></tag>
   <elementGuidId>81c489da-400a-460e-af31-6478ca47ce4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='transaction_form']/div/div/div/div/div/div/div/fieldset/div/div/div/div/label/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3be5c7a6-4da9-4b03-82cb-657981fa4458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>price-value</value>
      <webElementGuid>4a507e08-a6ec-49fc-8058-1937136f337c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$3,353.00</value>
      <webElementGuid>aa0a9c2d-5bb8-459f-ae4b-905f89f98736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transaction_form&quot;)/div[@class=&quot;l-grid&quot;]/div[@class=&quot;l-grid__cell l-grid__cell--8-col l-grid__cell--order-2-tablet l-grid__cell--order-2-phone&quot;]/div[@class=&quot;card card--large&quot;]/div[@class=&quot;card__content&quot;]/div[@class=&quot;card__text&quot;]/div[@class=&quot;card__section card__section--content&quot;]/div[@class=&quot;l-grid__cell l-grid__cell--12-col&quot;]/fieldset[1]/div[@class=&quot;radio-group&quot;]/div[1]/div[1]/div[@class=&quot;radio is-dirty&quot;]/label[@class=&quot;radio__label&quot;]/div[@class=&quot;price&quot;]/span[2]</value>
      <webElementGuid>2095bba3-2c1a-43d0-9e95-446ae93f5d7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='transaction_form']/div/div/div/div/div/div/div/fieldset/div/div/div/div/label/div/span[2]</value>
      <webElementGuid>5afab552-5667-42fa-8a8e-445a4842013d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[1]/following::span[1]</value>
      <webElementGuid>da20125e-d016-4371-817e-f55ec06190b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay in full'])[1]/following::span[2]</value>
      <webElementGuid>3c201c9b-21d6-4044-9980-c164c14d44b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay a minimum deposit'])[1]/preceding::span[1]</value>
      <webElementGuid>ae27202f-48af-4363-8f8c-e9427858d889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[2]/preceding::span[2]</value>
      <webElementGuid>5fe35913-475b-43c6-a107-c7ed3e8a5109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$3,353.00']/parent::*</value>
      <webElementGuid>38064c61-7a7c-49dd-98d5-9d5eb087e460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>477d7a8b-eac9-4538-b168-0d1ce5b6c3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$3,353.00' or . = '$3,353.00')]</value>
      <webElementGuid>50aa2d3a-47ff-44ed-8737-c9a814c687f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
