<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_7432621</name>
   <tag></tag>
   <elementGuidId>f0b54be9-58f1-4e67-9060-b00d65e3e3c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong.text--primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/main/div/div/div/div/p/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>fddebcf3-4165-45b2-949d-e3fb6d378af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text--primary</value>
      <webElementGuid>2a04ae83-6553-4d21-9533-aa4b28e9f8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 7432621 </value>
      <webElementGuid>783e665c-11b3-4b6c-b80f-36665f8d472d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[@class=&quot;l-main&quot;]/div[@class=&quot;l-container&quot;]/div[@class=&quot;l-grid&quot;]/div[@class=&quot;l-grid__cell l-grid__cell--4-col l-grid__cell--6-col-desktop&quot;]/div[@class=&quot;u-text-align--center&quot;]/p[1]/strong[@class=&quot;text--primary&quot;]</value>
      <webElementGuid>adac4c86-23fb-48d4-986a-11c1f39bc619</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/div/div/div/p/strong</value>
      <webElementGuid>f3a8f3d6-cc8c-4008-bccf-22c048b0bf47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='your booking is confirmed!'])[1]/following::strong[1]</value>
      <webElementGuid>98d07683-a448-47e9-8677-f91056b1bf22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cycle Sri Lanka'])[1]/preceding::strong[1]</value>
      <webElementGuid>4a3ae642-b97c-4ea7-89f7-7d80ae5c9a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trip'])[1]/preceding::strong[1]</value>
      <webElementGuid>b2dd5be2-6107-48aa-bf7c-41fd3191050c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7432621']/parent::*</value>
      <webElementGuid>07877fde-5ef7-40e8-ac44-980a8136114d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>ebdf3b4f-70fe-4e81-8a23-144f2d4fea19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = ' 7432621 ' or . = ' 7432621 ')]</value>
      <webElementGuid>4c51f486-ac30-4a94-9095-1a152ebce74e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
