<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Africa</name>
   <tag></tag>
   <elementGuidId>0744293e-77bf-4815-8a5a-47b768924577</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-bar']/div[2]/div/nav/div/nav/div/div/ul/li/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mega-menu__level-3-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>79044f67-8975-4dba-a867-860390c3a70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/africa</value>
      <webElementGuid>34474811-d3bb-47a0-904f-2a1f66e89755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>mega-menu__level-3-link</value>
      <webElementGuid>018e18cc-b685-4d55-acb6-4b2faf597a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mega-menu__level-3-title</value>
      <webElementGuid>2e0dd1f0-d860-4bc4-af92-4f4171807bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              Africa
            </value>
      <webElementGuid>edbe8258-d5fb-4507-91b8-1cc9012c3824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-bar&quot;)/div[@class=&quot;header-bar__bottom u-display--none md:u-display--block&quot;]/div[@class=&quot;header-bar__container header-bar__container--flex&quot;]/nav[@class=&quot;header-bar__bottom-left&quot;]/div[1]/nav[@class=&quot;mega-menu&quot;]/div[@class=&quot;mega-menu__level-1 mega-menu__level-1--visible&quot;]/div[@class=&quot;mega-menu__level-2&quot;]/ul[@class=&quot;mega-menu__level-2-items&quot;]/li[@class=&quot;mega-menu__level-2-item&quot;]/div[@class=&quot;mega-menu__level-3 mega-menu__level-3--visible&quot;]/a[@class=&quot;mega-menu__level-3-title&quot;]</value>
      <webElementGuid>1ee3d6f4-c4e4-4b1c-84f1-d639774dfad7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-bar']/div[2]/div/nav/div/nav/div/div/ul/li/div/a</value>
      <webElementGuid>575c616f-b1a7-4dbb-bd58-bfbd512d62f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Africa')]</value>
      <webElementGuid>c7ebffe2-d09e-414e-b2b4-51284be40087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Africa'])[1]/following::a[1]</value>
      <webElementGuid>6ff688b0-db3b-4c20-894e-6df15f5e83ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purpose'])[1]/following::a[1]</value>
      <webElementGuid>20c72681-398d-4fc3-8fb2-033872c2e479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Botswana'])[1]/preceding::a[1]</value>
      <webElementGuid>dede6fbd-ed2c-4c93-b8a3-49b4e70f5fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comoros Island'])[1]/preceding::a[2]</value>
      <webElementGuid>66487982-4680-4278-94bf-df68a0fd45d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/africa')]</value>
      <webElementGuid>7746daa6-9b60-4cfd-a420-f2a1ff34b93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/a</value>
      <webElementGuid>b3a7387e-c28c-40db-a7d9-c951851ae649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/africa' and (text() = '
              Africa
            ' or . = '
              Africa
            ')]</value>
      <webElementGuid>71836ce1-7028-4573-b8f6-c31dd2d0484b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
