<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Botswana</name>
   <tag></tag>
   <elementGuidId>3a7d0f51-1ad5-49f6-b5f8-ba55a1dc57b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-bar']/div[2]/div/nav/div/nav/div/div/ul/li/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mega-menu__level-3-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>55c724b9-a727-446e-8173-4f1c54aec5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/botswana</value>
      <webElementGuid>af1ccac1-3502-4354-94e6-fd124f97f903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>mega-menu__level-3-link</value>
      <webElementGuid>125151ef-5f91-40c6-8b4c-f6b2d27e48fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mega-menu__level-3-link</value>
      <webElementGuid>a4768abf-4456-434c-8476-7f7ea1f12b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Botswana
                </value>
      <webElementGuid>9a217b8a-46d6-42e5-abb7-e3686158e1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-bar&quot;)/div[@class=&quot;header-bar__bottom u-display--none md:u-display--block&quot;]/div[@class=&quot;header-bar__container header-bar__container--flex&quot;]/nav[@class=&quot;header-bar__bottom-left&quot;]/div[1]/nav[@class=&quot;mega-menu&quot;]/div[@class=&quot;mega-menu__level-1 mega-menu__level-1--visible&quot;]/div[@class=&quot;mega-menu__level-2&quot;]/ul[@class=&quot;mega-menu__level-2-items&quot;]/li[@class=&quot;mega-menu__level-2-item&quot;]/div[@class=&quot;mega-menu__level-3 mega-menu__level-3--visible&quot;]/ul[@class=&quot;mega-menu__level-3-items mega-menu__level-3-items--column-3&quot;]/li[@class=&quot;mega-menu__level-3-item&quot;]/a[@class=&quot;mega-menu__level-3-link&quot;]</value>
      <webElementGuid>59324bb5-d7cd-4b7c-b1ee-5b9be18ae118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-bar']/div[2]/div/nav/div/nav/div/div/ul/li/div/ul/li/a</value>
      <webElementGuid>6e2dfe0e-d132-4d4d-917f-3ef24028e089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Botswana')]</value>
      <webElementGuid>6c93e6c1-8927-4833-a974-4fdf1802e553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Africa'])[2]/following::a[1]</value>
      <webElementGuid>714252de-b521-40da-8705-40293135b92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Africa'])[1]/following::a[2]</value>
      <webElementGuid>d53a2ae1-b583-458f-9402-14d2471bfda7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comoros Island'])[1]/preceding::a[1]</value>
      <webElementGuid>18260840-bacf-4c0e-85d0-4d4b5454ce93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Djibouti'])[1]/preceding::a[2]</value>
      <webElementGuid>3a24de62-75cf-421c-8f93-74cabc47edf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Botswana']/parent::*</value>
      <webElementGuid>faddf30e-b13c-43f2-a146-d6a271f186de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/botswana')]</value>
      <webElementGuid>87bac84f-2b05-4b04-87d3-4b80ea5da50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/ul/li/a</value>
      <webElementGuid>eba1ca9f-9372-4c70-ab7a-660e9be4fbec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/botswana' and (text() = '
                  Botswana
                ' or . = '
                  Botswana
                ')]</value>
      <webElementGuid>f6838e38-c96f-40e6-8634-47d233b2091e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
