<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Destinations</name>
   <tag></tag>
   <elementGuidId>238ea990-d445-48b6-9d8f-519bb94ccb65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header-bar__navigation-link-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='header-bar__navigation-link-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07b9b7f2-2430-489c-b54a-6c07a22bd300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/top-destinations</value>
      <webElementGuid>3ec2d279-4a55-4e2a-a924-a55b75358e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-bar__navigation-link-1</value>
      <webElementGuid>9cf679c0-7a1c-4fcd-9199-27e7988409d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>header-bar-menu-item</value>
      <webElementGuid>b899dace-37a7-41c0-86bd-ac33e7181247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-bar__navigation-link header-bar__navigation-link--active</value>
      <webElementGuid>9a548d00-3f87-4086-8a81-8c43c9984b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Destinations
              </value>
      <webElementGuid>a7d36406-aa29-4c26-b5ed-6a79df37d49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-bar__navigation-link-1&quot;)</value>
      <webElementGuid>14e2756b-a5b4-4e6e-912a-40754dd3e279</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='header-bar__navigation-link-1']</value>
      <webElementGuid>51b37fe2-8848-4562-a927-8c5a352610a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-bar']/div[2]/div/nav/ul/li[2]/button</value>
      <webElementGuid>49a70b34-5a8d-48ef-9cfd-b1595daefd04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Booking'])[1]/following::button[2]</value>
      <webElementGuid>4c248bb6-4b9d-4f70-8e00-b4d5e2fe1fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Wishlist'])[1]/following::button[2]</value>
      <webElementGuid>ea6b67ee-a330-4072-95a1-38b9afeb68b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ways to travel'])[1]/preceding::button[1]</value>
      <webElementGuid>7b482290-a9ab-4308-ab2b-9e3d96c69903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deals'])[1]/preceding::button[2]</value>
      <webElementGuid>b150217b-003d-43e4-a89b-d0b165bac6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Destinations']/parent::*</value>
      <webElementGuid>7eb3704f-3687-40cd-9947-6e798e2daf29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button</value>
      <webElementGuid>d9d4cc09-a231-474b-b6bf-1e01a28a1406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@href = '/top-destinations' and @id = 'header-bar__navigation-link-1' and (text() = '
                Destinations
              ' or . = '
                Destinations
              ')]</value>
      <webElementGuid>c3f58211-f090-41d8-8301-c244c1588860</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
