<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Africa</name>
   <tag></tag>
   <elementGuidId>37fd12a4-0c1d-415d-8678-f2945ceccd6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-bar']/div[2]/div/nav/div/nav/div/div/ul/li/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mega-menu__level-2-link.mega-menu__level-2-link--active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a89abbe0-a8b2-4fe1-b68d-d52f2db0ea16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>mega-menu__level-2-link</value>
      <webElementGuid>cb42ac1c-e495-41be-b67d-89dbb6c65ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mega-menu__level-2-link mega-menu__level-2-link--active</value>
      <webElementGuid>185c3872-74c0-4490-8f3a-efee6b66dfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Africa
                </value>
      <webElementGuid>df7d1419-c824-46af-89f5-060115041505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-bar&quot;)/div[@class=&quot;header-bar__bottom u-display--none md:u-display--block&quot;]/div[@class=&quot;header-bar__container header-bar__container--flex&quot;]/nav[@class=&quot;header-bar__bottom-left&quot;]/div[1]/nav[@class=&quot;mega-menu&quot;]/div[@class=&quot;mega-menu__level-1 mega-menu__level-1--visible&quot;]/div[@class=&quot;mega-menu__level-2&quot;]/ul[@class=&quot;mega-menu__level-2-items&quot;]/li[@class=&quot;mega-menu__level-2-item&quot;]/button[@class=&quot;mega-menu__level-2-link mega-menu__level-2-link--active&quot;]</value>
      <webElementGuid>5f04b51a-024b-434b-a403-cf69ba43c0ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-bar']/div[2]/div/nav/div/nav/div/div/ul/li/button</value>
      <webElementGuid>3f8ff345-9e0b-4db8-b3c3-7a31329459d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purpose'])[1]/following::button[1]</value>
      <webElementGuid>bd5ba557-3072-4868-94fb-1d16b6295419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deals'])[1]/following::button[2]</value>
      <webElementGuid>87bb8ed0-92d3-4595-b55f-34429050c747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Africa'])[2]/preceding::button[1]</value>
      <webElementGuid>557097ab-9518-40a8-b1f2-f48295f10186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Botswana'])[1]/preceding::button[1]</value>
      <webElementGuid>efb3468d-fc5d-4d98-b591-05259b08b8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Africa']/parent::*</value>
      <webElementGuid>3b45c529-bebe-4893-bba4-c5991dacaa45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/button</value>
      <webElementGuid>15be1ae2-b809-4706-bd51-4d748511808a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
            Africa
                ' or . = '
            Africa
                ')]</value>
      <webElementGuid>f40b0969-ea6f-4a22-8cc6-f879545ffe67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
