<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel</name>
   <tag></tag>
   <elementGuidId>e4ad6516-a706-4081-b042-488bf3bd4965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login__form']/div[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-secondary.btn-block.cancel-button.cancel-button--sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9d80358b-92f3-460a-ac9a-69459bca4972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-block cancel-button cancel-button--sm</value>
      <webElementGuid>6e88383d-2a46-4cf5-bc63-6f4f03d5b612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.intrepidtravel.com.uat.internal/shortlist</value>
      <webElementGuid>9230c143-198f-4d75-ad4f-2e62ea6eb144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9ba270b-f6c3-4d45-ae66-4cc90894c515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>564cacdb-11b8-4fa8-8683-61bb1a23d40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login__form&quot;)/div[@class=&quot;button-group&quot;]/a[@class=&quot;btn btn-secondary btn-block cancel-button cancel-button--sm&quot;]</value>
      <webElementGuid>1366771a-d5d8-454b-ad01-15ef7e814aec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login__form']/div[7]/a</value>
      <webElementGuid>18e68fbf-a5d2-4089-97e2-9f3a907087cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel')]</value>
      <webElementGuid>f0685d09-b750-4cf6-8079-c603c289459c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View and manage your trip in My Booking'])[1]/following::a[1]</value>
      <webElementGuid>20cabd4a-6b05-465d-9439-58979f6ec5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::a[2]</value>
      <webElementGuid>67a8fa44-1c20-44ef-848e-7474575b22cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in to my wishlist'])[1]/preceding::a[1]</value>
      <webElementGuid>fd7974cd-087a-4a96-97be-0c95d1d8a46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::a[1]</value>
      <webElementGuid>46aab6ee-e61e-48c8-941c-ba0c607ac459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>a55bc2f0-d988-4c6a-9bfe-b781415c2a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.intrepidtravel.com.uat.internal/shortlist')]</value>
      <webElementGuid>71420b93-0e29-471e-8605-e6e0c09f7295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a</value>
      <webElementGuid>41ac857e-6b90-431c-a92b-7dfe1b74695b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.intrepidtravel.com.uat.internal/shortlist' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>e8dffa4e-2fc1-4616-98da-65d0f55ca9d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
