<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_2024</name>
   <tag></tag>
   <elementGuidId>9f55b63b-b0e6-452b-ba60-1ee75a5d251c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='2024']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.date-button-select__button.button--primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07153f3a-89bf-4977-868b-03fc92b2bee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button date-button-select__button button--primary</value>
      <webElementGuid>5bffc4e5-5b52-4b3c-9a84-32d04d92a927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>ab23ef1f-2009-45d4-a360-05bd3b513cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>84872dd6-2153-48a3-9f99-abf118b74342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dates-&amp;-availabilities&quot;)/div[1]/div[@class=&quot;u-margin-bottom--2 xs:u-padding-left--1 xs:u-padding-right--1 sm:u-padding-left--0 sm:u-padding-right--0&quot;]/div[@class=&quot;date-button-select&quot;]/div[@class=&quot;date-button-select__years&quot;]/button[@class=&quot;button date-button-select__button button--primary&quot;]</value>
      <webElementGuid>649f862f-6709-4f12-88fb-e34cbd1ff715</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='2024']</value>
      <webElementGuid>3741345e-a902-4e17-ae95-6c9b8726db44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dates-&amp;-availabilities']/div/div/div[2]/div/button[2]</value>
      <webElementGuid>ae649d41-d3b9-4759-acf3-b298b0167ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prices may go up, so secure your trip today'])[1]/following::button[2]</value>
      <webElementGuid>b2550843-99b5-4f09-b11f-22e09ac77de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dates and availability'])[2]/following::button[2]</value>
      <webElementGuid>14f38f56-334c-46f4-b761-145a32c3a5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan'])[1]/preceding::button[2]</value>
      <webElementGuid>e4139d24-a9fe-47fc-abc8-3487bd2c9c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feb'])[1]/preceding::button[3]</value>
      <webElementGuid>2bcc5d74-a9e4-4e57-925d-e3279b0cd078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2024']/parent::*</value>
      <webElementGuid>742e3222-e8b8-4810-8e4a-4659e07640ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button[2]</value>
      <webElementGuid>e92cf720-0678-4844-8d35-a9f3a4cf6fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '2024' or . = '2024')]</value>
      <webElementGuid>3c3f261e-dfff-4354-9848-55b098d7f330</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
