<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Jun</name>
   <tag></tag>
   <elementGuidId>c5a5d667-ffa4-426b-a482-7909dfe66e83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5c88f569-443a-48ec-853e-634333745266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--small sm:button date-button-select__button button--primary</value>
      <webElementGuid>4650f07a-693c-4ed1-8d03-dcc3503945f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>9e53a74e-cc17-405a-b061-738b85bf0362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jun</value>
      <webElementGuid>9155f2e1-eba6-4ce2-a978-1020904ff5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dates-&amp;-availabilities&quot;)/div[1]/div[@class=&quot;u-margin-bottom--2 xs:u-padding-left--1 xs:u-padding-right--1 sm:u-padding-left--0 sm:u-padding-right--0&quot;]/div[@class=&quot;date-button-select&quot;]/div[@class=&quot;date-button-select__months&quot;]/button[@class=&quot;button button--small sm:button date-button-select__button button--primary&quot;]</value>
      <webElementGuid>52c15123-3b64-41c3-a974-ffbb040f821a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='6']</value>
      <webElementGuid>46d19307-2b08-4dd2-9fbc-6fa048a9e313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Dates-&amp;-availabilities']/div/div/div[2]/div[2]/button[6]</value>
      <webElementGuid>f99dc27e-44a3-4593-a6e4-43d0f6540f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May'])[1]/following::button[1]</value>
      <webElementGuid>535e36d2-2a10-4563-8001-ec553b834915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apr'])[1]/following::button[2]</value>
      <webElementGuid>5fc45f87-3b56-4ac5-99b9-7d7b058d256c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jul'])[1]/preceding::button[1]</value>
      <webElementGuid>eb730555-cbf9-44ad-bd4a-689bf4742491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aug'])[1]/preceding::button[2]</value>
      <webElementGuid>f4a4cadc-13d0-4246-b32b-a9e7d7326a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jun']/parent::*</value>
      <webElementGuid>8f090733-93b3-4256-8849-1adc5a5e493d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[6]</value>
      <webElementGuid>845d449c-ff73-4a23-a99b-58585aa6f164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Jun' or . = 'Jun')]</value>
      <webElementGuid>7f0d8536-0f68-46a1-bbdc-c50c6e9015b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
