<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Botswana_banner__content</name>
   <tag></tag>
   <elementGuidId>b7e639fe-ce14-4cf6-846e-eac17243a1b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.banner__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/main/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73e02398-5913-4c49-8632-9164680bd534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>banner__content</value>
      <webElementGuid>997cf172-5d73-4151-96c4-6a9405166bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>banner__content</value>
      <webElementGuid>921b1e3d-2177-46e4-a4ac-0432f38ce74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[1]/main[1]/div[@class=&quot;page-banner&quot;]/div[@class=&quot;banner banner--xs-96-25 banner--sm-96-25 banner--md-96-25 banner--lg-96-25 banner--xl-96-25&quot;]/div[@class=&quot;banner__content&quot;]</value>
      <webElementGuid>4a8106b4-916d-4961-ad55-e6bbf9a16b55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/main/div/div/div[2]</value>
      <webElementGuid>383e5fb7-1549-44e8-ad4b-64daddd80d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div[2]</value>
      <webElementGuid>bbe3c6d9-d169-46d1-bbcd-a429f1dd45db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
